export const PHASES = [
  {
    id: 'preparation',
    name: 'Preparation',
    short: 'Prep',
    stage: 'pre-incident',
    description: 'Ensure people, tooling, and process are ready before an incident occurs.',
    tasks: [
      'Review and update the incident response plan',
      'Verify on-call rotation and escalation paths',
      'Confirm access to logging and monitoring (SIEM, EDR, cloud audit)',
      'Test communication channels (Slack war room, PagerDuty, conference bridge)',
      'Validate backup integrity and recovery procedures',
      'Ensure runbooks and contact lists are accessible offline',
      'Review current threat intelligence and known TTPs',
    ],
  },
  {
    id: 'identification',
    name: 'Identification',
    short: 'Identify',
    stage: 'response',
    description: 'Determine whether an event is a real incident, and document its scope.',
    tasks: [
      'Triage initial alert and rule out false positive',
      'Record time of detection and detection source',
      'Determine scope: affected hosts, users, accounts, data',
      'Classify incident type (malware, intrusion, data breach, DoS, insider)',
      'Assign incident commander and notify stakeholders',
      'Open incident ticket and start chain-of-custody log',
      'Capture initial indicators of compromise (IPs, hashes, domains, accounts)',
    ],
  },
  {
    id: 'containment',
    name: 'Containment',
    short: 'Contain',
    stage: 'response',
    description: 'Limit the blast radius — short-term and long-term containment.',
    tasks: [
      'Isolate affected hosts from the network (quarantine VLAN or EDR)',
      'Disable compromised user and service accounts',
      'Block malicious IPs, domains, and hashes at perimeter and EDR',
      'Preserve volatile evidence (memory, netstat, running processes)',
      'Snapshot affected systems before making changes',
      'Rotate exposed credentials, API keys, and tokens',
      'Notify legal and compliance if PII or regulated data is involved',
    ],
  },
  {
    id: 'eradication',
    name: 'Eradication',
    short: 'Eradicate',
    stage: 'response',
    description: 'Remove the threat and close the door behind it.',
    tasks: [
      'Identify and remove malware and persistence mechanisms',
      'Patch exploited vulnerabilities across the environment',
      'Remove unauthorized accounts, keys, and scheduled tasks',
      'Validate the threat actor no longer has access',
      'Sweep environment for additional IOCs and lateral movement',
      'Update detection rules and EDR policies with new IOCs',
    ],
  },
  {
    id: 'recovery',
    name: 'Recovery',
    short: 'Recover',
    stage: 'response',
    description: 'Bring systems back to production safely and watch for recurrence.',
    tasks: [
      'Restore systems from known-clean backups or rebuild from gold image',
      'Reset credentials for all affected accounts and force re-auth',
      'Return systems to production in monitored mode',
      'Verify normal operations with system owners',
      'Communicate restoration status to stakeholders and customers',
      'Maintain heightened monitoring on affected systems for 30 days',
    ],
  },
  {
    id: 'lessons',
    name: 'Lessons Learned',
    short: 'Lessons',
    stage: 'post-incident',
    description: 'Close the loop. Make the next incident shorter than this one.',
    tasks: [
      'Schedule post-incident review within two weeks of resolution',
      'Document full timeline of events with timestamps',
      'Identify root cause and contributing factors',
      'Capture what worked, what failed, and what surprised the team',
      'Create action items with named owners and deadlines',
      'Update runbooks, detection rules, and the IR plan',
      'Share sanitized findings with the broader engineering org',
    ],
  },
];

export const SEVERITIES = {
  Low: {
    label: 'Low',
    accent: 'bg-sky-500',
    accentText: 'text-sky-400',
    accentBorder: 'border-sky-500/40',
    accentSoft: 'bg-sky-500/10',
    ring: 'ring-sky-500/30',
    glow: 'shadow-sky-500/20',
    description: 'Minor impact, no customer effect',
  },
  Medium: {
    label: 'Medium',
    accent: 'bg-amber-500',
    accentText: 'text-amber-400',
    accentBorder: 'border-amber-500/40',
    accentSoft: 'bg-amber-500/10',
    ring: 'ring-amber-500/30',
    glow: 'shadow-amber-500/20',
    description: 'Limited impact or degraded service',
  },
  High: {
    label: 'High',
    accent: 'bg-orange-500',
    accentText: 'text-orange-400',
    accentBorder: 'border-orange-500/40',
    accentSoft: 'bg-orange-500/10',
    ring: 'ring-orange-500/30',
    glow: 'shadow-orange-500/20',
    description: 'Significant customer or data impact',
  },
  Critical: {
    label: 'Critical',
    accent: 'bg-rose-500',
    accentText: 'text-rose-400',
    accentBorder: 'border-rose-500/40',
    accentSoft: 'bg-rose-500/10',
    ring: 'ring-rose-500/30',
    glow: 'shadow-rose-500/20',
    description: 'Active breach, outage, or regulatory exposure',
  },
};
